### ISSUE TITLE
Default LCIO Input File for `fcceeConfig/fccReconstruction.xml` does not exist anymore

### ISSUE THREAD

**Issue by vvolkl** [iLCSoft/CLICPerformance#131]
```
cp: cannot stat ‘/afs/cern.ch/work/e/eleogran/public/mu_sim/mu_validation_50kevents.slcio’: No such file or directory
```

**Comment by andresailer** [comment]
@ebrondol

**Comment by andresailer** [comment]
Or change to the file in Tests

**Comment by ebrondol** [comment]
This file does not exist anymore and I dont see any replacement in the same folder.

**Comment by eleogran** [comment]
Ciao! I still receive the mail from this trend.
The file was a simple set of 50k simulated muons with fixed energy uniform theta distribution.
$ ddsim --steeringFile $ILCSOFT/ClicPerformance/HEAD/fcceeConfig/fcc_steer.py  --compactFile $ILCSOFT/lcgeo/HEAD/Fccee/compact/<WHATEVERMODEL>.xml --enableGun --gun.particle mu- --gun.energy 10*GeV  --gun.distribution uniform --outputFile mu_validation_50kevents.slcio --numberOfEvents 50000
